### ISSUE TITLE
In Feetech back-end, add possibility of offsetting joints

### ISSUE THREAD

**Issue by Bardo91** [ViGUS/hecatonquiros#34]

**Comment by Bardo91** [comment]
Have you fixed this? @manuoso

**Comment by manuoso** [comment]
We have now a tool for finer tune (MinMaxValues in map angle) but not implemented offset to these finer tune

**Comment by Bardo91** [comment]
Well, I consider that this  tool is what we wanted. What I meant is if the code allows to use these values to each arm separately, or otherwise it is still hardcoded in the Arm4DoF class.

**Comment by manuoso** [comment]
Ahh, Its still hardcoded in the Arm3DoF class, you receive these values and then you must put them in the class

**Comment by Bardo91** [comment]
Ok, thanks

**Comment by manuoso** [comment]
added option for use a xml for configure offsets
