### ISSUE TITLE
Operating System Query 

### ISSUE THREAD

**Issue by asha176** [ViGUS/hecatonquiros#61]
Does hecatonquiros works well on windows or should I install ubuntu in vm ?

**Comment by Bardo91** [comment]
Dear @asha176, it has been tested just in Ubuntu. It is very likely that it might not work, due to the dependencies. You may try to compile all of them in Windows, but it might be easier to run it in an VM.

**Comment by asha176** [comment]
ros1 or ros2 ?

**Comment by asha176** [comment]
should we use ros1 or ros2 to execute hecatonquiros ?
